# Generated by Django 5.0.4 on 2024-05-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_alter_experience_category_alter_experience_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
