# Generated by Django 5.0.4 on 2024-04-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_category'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='experience',
            field=models.ManyToManyField(blank=True, null=True, to='experiences.experience'),
        ),
    ]
