# Generated by Django 5.0.4 on 2024-04-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_category'),
        ('wishlists', '0002_alter_wishlist_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, to='rooms.room'),
        ),
    ]
